# Generated by Django 5.1.7 on 2025-08-19 20:18

import django.core.files.storage
import skills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0022_assignedtest_student_feedback_studentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Student profile picture (saved in static/student_images/)', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Pawan\\Desktop\\pawanskills\\skills\\static'), upload_to=skills.models.student_profile_pic_path),
        ),
    ]
